### ISSUE TITLE
Compare md5deep vs. walk_to_dfxml DFXML outputs

### ISSUE THREAD

**Issue by tw4l** [timothyryanwalsh/cca-diskimageprocessor#19]
https://github.com/simsong/dfxml/blob/master/python/walk_to_dfxml.py

**Comment by jesswhyte** [comment]
Which checks for file type!

**Comment by tw4l** [comment]
@jesswhyte I know, right? Didn't even know this existed until I met @ajnelson-nist, who maintains the DFXML Python bindings, at the BitCurator User Forum. I'm going to do some tests but will likely replace md5deep with this soon.

**Comment by jesswhyte** [comment]
Neither did I, very cool. 

Reminder to self: look through the rest of the python scripts :-)

**Comment by tw4l** [comment]
md5deep replaced by walk_to_dfxml.py with merge https://github.com/timothyryanwalsh/cca-diskimageprocessor/commit/76d2d7e33f0ece161d502f81be0ac6759f09ff70
