### ISSUE TITLE
Look into importing DFXML bindings from submodule

### ISSUE THREAD

**Issue by tw4l** [timothyryanwalsh/cca-diskimageprocessor#20]
See: https://github.com/cul-it/hfs2dfxml/tree/python3

**Comment by dd388** [comment]
Let me know if you want me to do a fork to set it up... I feel fancy having learned how to do it now.

**Comment by tw4l** [comment]
Yes please! That would be amazing. I very quickly tried in a local fork but think I was missing a step somewhere.

**Comment by dd388** [comment]
Ok, I just made a pull request. Submodules ahoy!

**Comment by tw4l** [comment]
Fixed with merge https://github.com/timothyryanwalsh/cca-diskimageprocessor/pull/23
